export const availableIcons = [
    "cake",
    "celebration",
    "emoji-events",
    "event",
    "favorite",
    "flight",
    "gift",
    "grade",
    "home",
    "movie",
    "music-note",
    "restaurant",
    "school",
    "sports",
    "star",
    "thumb-up",
    "trophy",
    "trophy-award",
    "verified",
    "work",
  ];
  
  export const availableColors = [
    "#000000",
    "#FF0000",
    "#00FF00",
    "#0000FF",
    "#FFA500",
    "#800080",
    "#FFC0CB",
  ];